### ISSUE TITLE
packages: Show package dependencies and dependants

### ISSUE THREAD

**Issue by davetcoleman** [rosindex/rosindex#66]
Similar to how the ROS wiki currently does it?

I think this is low priority though

**Comment by jbohren** [comment]
Yeah, this should be there.

**Comment by jbohren** [comment]
added package depends, I'll add the depends-on stuff later

**Comment by jbohren** [comment]
Now that [rosdeps](http://rosindex.github.io/deps/) are indexed, I can fill this stuff out.

**Comment by jbohren** [comment]
Now with deps and dependants: http://rosindex.github.io/p/base_local_planner/#hydro-deps

**Comment by gavanderhoorn** [comment]
+many. Took some time understand the difference between clicking on the arrows and the dependants themselves, but this is nice.

**Comment by jbohren** [comment]
I'm going to close this now that the dependants are fleshed out. Feel free to reopen if you want more.

**Comment by davetcoleman** [comment]
Thanks, great work!
